fastlane_version '2.157'
default_platform :ios

platform :ios do
  desc 'Builds the iOS project'
  lane :build do
    # Assuming you're using xcodebuild for building, modify as needed
    xcodebuild(
      scheme: 'YourScheme',
      workspace: 'YourWorkspace.xcworkspace',
      configuration: 'Debug',
      clean: true,
      build: true
    )
  end

  desc 'Executes unit tests'
  lane :unit_test do |options|
    scan(
      scheme: 'YourScheme', # Ensure you specify your scheme
      clean: options[:clean] || false,
      skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution] || false
    )
  end
end
