fastlane_version '2.157'
default_platform :ios

platform :ios do
  desc "Builds the iOS project"
  lane :build do
    gym(
      workspace: "SE491GroupProject.xcodeproj/project.xcworkspace",
      scheme: "SE491GroupProject",
      sdk: "iphonesimulator",
      derived_data_path: "Build/",
      clean: true,
      xcargs: '-parallelizeTargets'
    )
  end

  desc 'Executes unit tests'
  lane :unit_test do |options|
    scan(
      clean: options[:clean],
      skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution]
    )
  end
end
