name: iOS CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode
      run: sudo xcode-select -s '/Applications/Xcode_15.3.app'

    - name: Install dependencies
      run: |
        gem install fastlane
        fastlane install_plugins

    - name: Build
      run: xcodebuild -scheme YourScheme -sdk iphoneos -configuration Debug build

    - name: Run Unit Tests
      run: fastlane scan --scheme YourScheme

    - name: UI Tests
      run: fastlane scan --scheme YourScheme --test_without_building --only_testing:UITests
